export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const RESET_COMMENTS = 'RESET_COMMENTS';
