export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECIEVE_COMMENTS = 'RECEIVE_COMMENTS';
export const CREATE_COMMENT = 'CREATE_COMMENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
