export const FETCH_SPOTS = 'FETCH_SPOTS';
export const REQUEST_SPOTS = 'REQUEST_SPOTS';
export const RECEIVE_SPOTS = 'RECEIVE_SPOTS';
export const CREATE_SPOT = 'CREATE_SPOT';
export const MODIFY_SPOT = 'MODIFY_SPOT';
export const REMOVE_SPOT = 'REMOVE_SPOT';
export const REMOVE_REQUEST_SPOT = 'REMOVE_REQUEST_SPOT';
export const LIKE_SPOT = 'LIKE_SPOT';

export const SET_SPOT_FORM = 'SET_SPOT_FORM';
export const UPDATE_SPOT_FORM = 'UPDATE_SPOT_FORM';
export const RESET_SPOT_FORM = 'RESET_SPOT_FORM';
